fix: Implement urlencoding
ovh/beamium pull request #131
Opened 2021-07-07 14:09 UTC by bubu11e

Implement urlencoding for class, labels key and labels value before sending data to warp10.

2021-07-07 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ovh/beamium?pullRequest=131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ovh/beamium?pullRequest=131) before we can accept your contribution.<br/><hr/>**Julien Girard** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ovh/beamium?pullRequest=131) it.</sub>

2021-07-08 13:54 UTC, Alkorin commented on src/lib/transcompiler.rs
> +                .map(|v| v.replace("\"", ""))
```suggestion
                .map(|v| v.replace("}", "")) // Remove last curly brace
                .map(|v| v.replace("\"", "")) // Remove quotes
```

2021-07-09 08:24 UTC, Alkorin approved these changes

2021-07-09 12:42 UTC, FlorentinDUBOIS requested changes
Thanks for the pull request! Could you add some unit tests around the encoding?

2021-07-09 12:42 UTC, FlorentinDUBOIS commented on Cargo.toml
> +urlencoding = "1.0.0"
The latest version of this package is the 1.3.3

2021-07-09 12:42 UTC, FlorentinDUBOIS commented on src/lib/transcompiler.rs
> +extern crate urlencoding;
The instruction `extern crate` is useless as you import the crate just below using `use`. The only benefit of using `extern crate` is by combining it with `#[macro_use]` at the beginning of the `main.rs` file

2021-07-09 12:42 UTC, FlorentinDUBOIS commented on src/lib/transcompiler.rs
> +            let mut labels = String::from("");
```suggestion
            let mut labels = String::new();
```

2021-07-09 12:42 UTC, FlorentinDUBOIS commented on src/lib/transcompiler.rs
> +            let mut buffer = String::from("");
```suggestion
            let mut buffer = String::new();
```

2021-07-09 12:42 UTC, FlorentinDUBOIS commented on src/lib/transcompiler.rs
> +                        buffer = String::from("");
```suggestion
                        buffer = String::new();
```

2021-07-09 15:25 UTC, FlorentinDUBOIS approved these changes

2021-07-15 09:05 UTC, merged